from __future__ import annotations

import sqlite3
from pathlib import Path
from urllib.parse import unquote, urlparse


class BaseRepository:
    placeholder = '?'

    def connect(self):
        raise NotImplementedError

    def sql(self, query: str) -> str:
        return query if self.placeholder == '?' else query.replace('?', self.placeholder)


class SqliteRepository(BaseRepository):
    def __init__(self, database_url: str):
        self.database_url = database_url

    def connect(self):
        parsed = urlparse(self.database_url)
        if parsed.scheme == 'sqlite':
            path = unquote(f'{parsed.netloc}{parsed.path}')
            if path.startswith('//'):
                path = path[1:]
            if not path:
                path = ':memory:'
        else:
            path = self.database_url
        if path != ':memory:':
            parent = Path(path).expanduser().absolute().parent
            parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(path)
        conn.row_factory = sqlite3.Row
        return conn


class PostgresRepository(BaseRepository):
    placeholder = '%s'

    def __init__(self, database_url: str):
        self.database_url = database_url

    def connect(self):
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(self.database_url, row_factory=dict_row)


class QuestRepository:
    def __init__(self, repo: BaseRepository):
        self.repo = repo

    def _execute(self, cur, query, params=()):
        return cur.execute(self.repo.sql(query), params)

    def _executemany(self, cur, query, params):
        return cur.executemany(self.repo.sql(query), params)

    def apply_migrations(self, now_iso: str):
        c = self.repo.connect(); cur = c.cursor()
        self._execute(cur, 'CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)')
        version = self._execute(cur, 'SELECT COALESCE(MAX(version), 0) AS v FROM schema_migrations').fetchone()['v']
        if version < 1:
            if self.repo.placeholder == '?':
                self._execute(cur, 'CREATE TABLE quests (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,final_location TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,quest_time_limit_sec INTEGER)')
                self._execute(cur, 'CREATE TABLE steps (id INTEGER PRIMARY KEY AUTOINCREMENT,quest_id INTEGER NOT NULL,idx INTEGER NOT NULL,prompt TEXT NOT NULL,password TEXT NOT NULL,step_time_limit_sec INTEGER,FOREIGN KEY(quest_id) REFERENCES quests(id))')
                self._execute(cur, 'CREATE TABLE participants (id INTEGER PRIMARY KEY AUTOINCREMENT,quest_id INTEGER NOT NULL,token TEXT NOT NULL UNIQUE,current_step INTEGER NOT NULL DEFAULT 1,started_at TEXT,step_started_at TEXT,locked_until TEXT,completed INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(quest_id) REFERENCES quests(id))')
                self._execute(cur, 'CREATE TABLE attempts (id INTEGER PRIMARY KEY AUTOINCREMENT,participant_id INTEGER NOT NULL,step_idx INTEGER NOT NULL,entered_password TEXT NOT NULL,success INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(participant_id) REFERENCES participants(id))')
            else:
                self._execute(cur, 'CREATE TABLE quests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title TEXT NOT NULL,final_location TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,quest_time_limit_sec INTEGER)')
                self._execute(cur, 'CREATE TABLE steps (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,quest_id BIGINT NOT NULL,idx INTEGER NOT NULL,prompt TEXT NOT NULL,password TEXT NOT NULL,step_time_limit_sec INTEGER,FOREIGN KEY(quest_id) REFERENCES quests(id))')
                self._execute(cur, 'CREATE TABLE participants (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,quest_id BIGINT NOT NULL,token TEXT NOT NULL UNIQUE,current_step INTEGER NOT NULL DEFAULT 1,started_at TEXT,step_started_at TEXT,locked_until TEXT,completed INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(quest_id) REFERENCES quests(id))')
                self._execute(cur, 'CREATE TABLE attempts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,participant_id BIGINT NOT NULL,step_idx INTEGER NOT NULL,entered_password TEXT NOT NULL,success INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(participant_id) REFERENCES participants(id))')
            self._execute(cur, 'INSERT INTO schema_migrations(version, applied_at) VALUES (?,?)', (1, now_iso))
        if version < 2:
            if self.repo.placeholder == '?':
                self._execute(cur, "ALTER TABLE participants ADD COLUMN status TEXT NOT NULL DEFAULT 'new'")
            else:
                self._execute(cur, "ALTER TABLE participants ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'new'")
            self._execute(cur, 'INSERT INTO schema_migrations(version, applied_at) VALUES (?,?)', (2, now_iso))
        if version < 3:
            if self.repo.placeholder == '?':
                self._execute(
                    cur,
                    'CREATE TABLE audit_events (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT, metadata TEXT, ip TEXT)',
                )
                self._execute(cur, 'CREATE INDEX idx_audit_events_created_at ON audit_events(created_at)')
                self._execute(cur, 'CREATE INDEX idx_audit_events_action ON audit_events(action)')
            else:
                self._execute(
                    cur,
                    'CREATE TABLE audit_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT, metadata TEXT, ip TEXT)',
                )
                self._execute(cur, 'CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON audit_events(created_at)')
                self._execute(cur, 'CREATE INDEX IF NOT EXISTS idx_audit_events_action ON audit_events(action)')
            self._execute(cur, 'INSERT INTO schema_migrations(version, applied_at) VALUES (?,?)', (3, now_iso))
        if version < 4:
            if self.repo.placeholder == '?':
                self._execute(cur, 'ALTER TABLE quests ADD COLUMN title_en TEXT')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN prompt_en TEXT')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN next_on_success_idx INTEGER')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN max_attempts INTEGER')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN penalty_sec INTEGER')
                self._execute(cur, 'CREATE TABLE quest_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, quest_id INTEGER NOT NULL, version INTEGER NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL)')
                self._execute(cur, 'CREATE TABLE quest_run_archive (id INTEGER PRIMARY KEY AUTOINCREMENT, participant_id INTEGER NOT NULL, quest_id INTEGER NOT NULL, token TEXT NOT NULL, status TEXT NOT NULL, completed INTEGER NOT NULL, archived_at TEXT NOT NULL, payload_json TEXT NOT NULL)')
            else:
                self._execute(cur, 'ALTER TABLE quests ADD COLUMN IF NOT EXISTS title_en TEXT')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN IF NOT EXISTS prompt_en TEXT')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN IF NOT EXISTS next_on_success_idx INTEGER')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN IF NOT EXISTS max_attempts INTEGER')
                self._execute(cur, 'ALTER TABLE steps ADD COLUMN IF NOT EXISTS penalty_sec INTEGER')
                self._execute(cur, 'CREATE TABLE IF NOT EXISTS quest_versions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, quest_id BIGINT NOT NULL, version INTEGER NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL)')
                self._execute(cur, 'CREATE TABLE IF NOT EXISTS quest_run_archive (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, participant_id BIGINT NOT NULL, quest_id BIGINT NOT NULL, token TEXT NOT NULL, status TEXT NOT NULL, completed INTEGER NOT NULL, archived_at TEXT NOT NULL, payload_json TEXT NOT NULL)')
            self._execute(cur, 'INSERT INTO schema_migrations(version, applied_at) VALUES (?,?)', (4, now_iso))
        c.commit(); c.close()

    def seed_demo(self, now_iso: str, token: str):
        c = self.repo.connect(); cur = c.cursor()
        q = self._execute(cur, 'SELECT COUNT(*) AS c FROM quests').fetchone()['c']
        if q == 0:
            self._execute(
                cur,
                'INSERT INTO quests(title, final_location, active, quest_time_limit_sec) VALUES (?,?,?,?)',
                ('Тайна четырёх ключей', 'Финальная точка: старый сундук в библиотеке', 1, 5400),
            )
            quest_id = cur.lastrowid if self.repo.placeholder == '?' else self._execute(cur, 'SELECT currval(pg_get_serial_sequence(\'quests\',\'id\')) AS id').fetchone()['id']
            steps = [
                (quest_id, 1, 'Ключ 1: Без рук, без ног, а ворота открывает. Что это?', 'КЛЮЧ', 900),
                (quest_id, 2, 'Ключ 2: Висит груша — нельзя скушать. Назови предмет.', 'ЛАМПОЧКА', 900),
                (quest_id, 3, 'Ключ 3: Меня теряют, когда спешат. Меня ищут в карманах. Что это?', 'ТЕЛЕФОН', 900),
                (quest_id, 4, 'Ключ 4: Я храню тайны и запираюсь на замок. Где лежат старые бумаги?', 'ШКАТУЛКА', 900),
            ]
            self._executemany(cur, 'INSERT INTO steps(quest_id,idx,prompt,password,step_time_limit_sec) VALUES (?,?,?,?,?)', steps)
            self._execute(cur, 'INSERT INTO participants(quest_id, token, started_at, step_started_at) VALUES (?,?,?,?)', (quest_id, token, now_iso, now_iso))
            c.commit()
        c.close()


def create_repository(database_url: str) -> BaseRepository:
    scheme = urlparse(database_url).scheme
    if scheme in ('', 'sqlite'):
        return SqliteRepository(database_url)
    if scheme in ('postgres', 'postgresql'):
        return PostgresRepository(database_url)
    raise ValueError(f'Unsupported database scheme: {scheme}')
